spring.application.name=core-service
server.port=8081

#  PostgresSql config
spring.datasource.url=jdbc:postgresql://localhost:5432/grocery_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# File upload (CSV bulk upload)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# SMTP — fill in your Gmail + App Password
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=YOUR_GMAIL@gmail.com
#spring.mail.password=YOUR_16_CHAR_APP_PASSWORD
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#SendGrid — fill in your SendGrid API key
sendgrid.api.key=your_sendgrid_api_key_here
sendgrid.from.email=your_sendgrid_mail_id_here